---
language: c
sudo: required

services:
    - docker

cache:
  directories:
    - $HOME/docker

before_install:
  - '__rvm_unload ; rm -rf ~/.rvm'
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo pip install ansible==2.2.0

script:
  - cd tests
  - docker-compose up -d
  - ansible-playbook user.yml -l centos
  - ansible-playbook user.yml -l debian
  - ansible-playbook user.yml -l ubuntu

before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
